"""Add operation_type and module_name to admin_log

Revision ID: eced0759cf66
Revises: 96eb87438fa5
Create Date: 2025-11-22 14:53:34.071742

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eced0759cf66'
down_revision = '96eb87438fa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oper_log')
    op.drop_table('login_info')
    op.drop_table('sys_dictionarylist')
    op.drop_table('task_log')
    op.drop_table('sys_department')
    op.drop_table('sys_quartzlog')
    op.drop_table('task')
    op.drop_table('sys_quartzoptions')
    op.drop_table('sys_workflowtableauditlog')
    op.drop_table('pear_config')
    op.drop_table('sys_workflowstep')
    op.drop_table('sys_tableinfo')
    op.drop_table('sys_workflow')
    op.drop_table('role')
    op.drop_table('sys_city')
    op.drop_table('sys_workflowtablestep')
    op.drop_table('sys_tablecolumn')
    op.drop_table('sys_user')
    op.drop_table('admin')
    op.drop_table('sys_userdepartment')
    op.drop_table('sys_role')
    op.drop_table('sys_workflowtable')
    op.drop_table('sys_dictionary')
    op.drop_table('sys_province')
    op.drop_table('auth')
    op.drop_table('admin_online')
    op.drop_table('sys_menu')
    with op.batch_alter_table('sys_conf', schema=None) as batch_op:
        batch_op.drop_index('type')

    op.drop_table('sys_conf')
    op.drop_table('task_server')
    op.drop_table('sys_log')
    op.drop_table('sys_roleauth')
    op.drop_table('role_auth')
    with op.batch_alter_table('admin_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('operation_type', sa.String(length=50), nullable=True, comment='操作类型'))
        batch_op.add_column(sa.Column('module_name', sa.String(length=50), nullable=True, comment='模块名称'))

    with op.batch_alter_table('renji_appointment', schema=None) as batch_op:
        batch_op.alter_column('PatientID',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.String(length=255),
               existing_comment='患者ID',
               existing_nullable=True)
        batch_op.alter_column('AppointmentTime',
               existing_type=mysql.DATETIME(),
               type_=sa.String(length=255),
               existing_comment='预约时间',
               existing_nullable=True)
        batch_op.alter_column('Remarks',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_comment='备注',
               existing_nullable=True)
        batch_op.drop_column('PatientNo')

    with op.batch_alter_table('renji_auxiliaryexaminationes', schema=None) as batch_op:
        batch_op.alter_column('RecordID',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True,
               existing_comment='病历ID')
        batch_op.alter_column('Remarks',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_comment='备注',
               existing_nullable=True)

    with op.batch_alter_table('renji_cnmedicine', schema=None) as batch_op:
        batch_op.alter_column('MedicineID',
               existing_type=mysql.VARCHAR(length=36),
               comment='检查ID',
               existing_comment='中药ID',
               existing_nullable=False)
        batch_op.alter_column('Remarks',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_comment='备注',
               existing_nullable=True)

    with op.batch_alter_table('renji_coursesofdisease', schema=None) as batch_op:
        batch_op.alter_column('PatientID',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True,
               existing_comment='患者ID')
        batch_op.alter_column('DiagnosticID',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True,
               existing_comment='诊断')
        batch_op.alter_column('Remarks',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_comment='备注',
               existing_nullable=True)

    with op.batch_alter_table('renji_diagnostic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('PatientID', sa.String(length=36), nullable=True, comment='患者ID'))
        batch_op.alter_column('Remarks',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_comment='备注',
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'renji_patients', ['PatientID'], ['PatientID'])

    with op.batch_alter_table('renji_examlib', schema=None) as batch_op:
        batch_op.add_column(sa.Column('PatientID', sa.String(length=36), nullable=True, comment='患者ID'))
        batch_op.alter_column('Remarks',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_comment='备注',
               existing_nullable=True)
        batch_op.drop_table_comment(
        'renji_examlib',
        existing_comment='检查',
        schema=None
    )
        batch_op.drop_column('AttachMents')

    with op.batch_alter_table('renji_patientmedicalhistories', schema=None) as batch_op:
        batch_op.alter_column('PatientID',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True,
               existing_comment='患者ID')
        batch_op.alter_column('HistoryType',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True,
               existing_comment='病史类型')
        batch_op.alter_column('Remarks',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_comment='小结',
               existing_nullable=True)
        batch_op.alter_column('CustomerType',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_comment='推荐人',
               existing_nullable=True)
        batch_op.drop_table_comment(
        'renji_patientmedicalhistories',
        existing_comment='患者病史',
        schema=None
    )

    with op.batch_alter_table('renji_patients', schema=None) as batch_op:
        batch_op.alter_column('Name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True,
               existing_comment='患者姓名')
        batch_op.alter_column('PatientNo',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True,
               existing_comment='患者编号')
        batch_op.alter_column('Birthday',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_comment='生日',
               existing_nullable=True)
        batch_op.alter_column('Remarks',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_comment='备注信息',
               existing_nullable=True)
        batch_op.alter_column('CustomerType',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_comment='推荐人',
               existing_nullable=True)

    with op.batch_alter_table('renji_records', schema=None) as batch_op:
        batch_op.alter_column('PatientID',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True,
               existing_comment='患者ID')
        batch_op.alter_column('OtherDiagnosis',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True,
               existing_comment='他院诊断')
        batch_op.alter_column('Remarks',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               comment='备注信息',
               existing_comment='备注',
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'renji_patients', ['PatientID'], ['PatientID'])

    with op.batch_alter_table('renji_westmedicine', schema=None) as batch_op:
        batch_op.alter_column('Remarks',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               comment='备注信息',
               existing_comment='备注',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('renji_westmedicine', schema=None) as batch_op:
        batch_op.alter_column('Remarks',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               comment='备注',
               existing_comment='备注信息',
               existing_nullable=True)

    with op.batch_alter_table('renji_records', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('Remarks',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               comment='备注',
               existing_comment='备注信息',
               existing_nullable=True)
        batch_op.alter_column('OtherDiagnosis',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False,
               existing_comment='他院诊断')
        batch_op.alter_column('PatientID',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False,
               existing_comment='患者ID')

    with op.batch_alter_table('renji_patients', schema=None) as batch_op:
        batch_op.alter_column('CustomerType',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_comment='推荐人',
               existing_nullable=True)
        batch_op.alter_column('Remarks',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_comment='备注信息',
               existing_nullable=True)
        batch_op.alter_column('Birthday',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_comment='生日',
               existing_nullable=True)
        batch_op.alter_column('PatientNo',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False,
               existing_comment='患者编号')
        batch_op.alter_column('Name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False,
               existing_comment='患者姓名')

    with op.batch_alter_table('renji_patientmedicalhistories', schema=None) as batch_op:
        batch_op.create_table_comment(
        'renji_patientmedicalhistories',
        '患者病史',
        existing_comment=None,
        schema=None
    )
        batch_op.alter_column('CustomerType',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_comment='推荐人',
               existing_nullable=True)
        batch_op.alter_column('Remarks',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_comment='小结',
               existing_nullable=True)
        batch_op.alter_column('HistoryType',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False,
               existing_comment='病史类型')
        batch_op.alter_column('PatientID',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False,
               existing_comment='患者ID')

    with op.batch_alter_table('renji_examlib', schema=None) as batch_op:
        batch_op.add_column(sa.Column('AttachMents', mysql.TEXT(), nullable=True, comment='附件'))
        batch_op.create_table_comment(
        'renji_examlib',
        '检查',
        existing_comment=None,
        schema=None
    )
        batch_op.alter_column('Remarks',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_comment='备注',
               existing_nullable=True)
        batch_op.drop_column('PatientID')

    with op.batch_alter_table('renji_diagnostic', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('Remarks',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_comment='备注',
               existing_nullable=True)
        batch_op.drop_column('PatientID')

    with op.batch_alter_table('renji_coursesofdisease', schema=None) as batch_op:
        batch_op.alter_column('Remarks',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_comment='备注',
               existing_nullable=True)
        batch_op.alter_column('DiagnosticID',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False,
               existing_comment='诊断')
        batch_op.alter_column('PatientID',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False,
               existing_comment='患者ID')

    with op.batch_alter_table('renji_cnmedicine', schema=None) as batch_op:
        batch_op.alter_column('Remarks',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_comment='备注',
               existing_nullable=True)
        batch_op.alter_column('MedicineID',
               existing_type=mysql.VARCHAR(length=36),
               comment='中药ID',
               existing_comment='检查ID',
               existing_nullable=False)

    with op.batch_alter_table('renji_auxiliaryexaminationes', schema=None) as batch_op:
        batch_op.alter_column('Remarks',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_comment='备注',
               existing_nullable=True)
        batch_op.alter_column('RecordID',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False,
               existing_comment='病历ID')

    with op.batch_alter_table('renji_appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('PatientNo', mysql.VARCHAR(length=36), nullable=True, comment='患者编号'))
        batch_op.alter_column('Remarks',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_comment='备注',
               existing_nullable=True)
        batch_op.alter_column('AppointmentTime',
               existing_type=sa.String(length=255),
               type_=mysql.DATETIME(),
               existing_comment='预约时间',
               existing_nullable=True)
        batch_op.alter_column('PatientID',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=36),
               existing_comment='患者ID',
               existing_nullable=True)

    with op.batch_alter_table('admin_log', schema=None) as batch_op:
        batch_op.drop_column('module_name')
        batch_op.drop_column('operation_type')

    op.create_table('role_auth',
    sa.Column('auth_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('role_id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=False, nullable=True),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sys_roleauth',
    sa.Column('Auth_Id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('AuthValue', mysql.TEXT(), nullable=False),
    sa.Column('CreateDate', mysql.DATETIME(), nullable=True),
    sa.Column('Creator', mysql.TEXT(), nullable=True),
    sa.Column('Menu_Id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('Modifier', mysql.TEXT(), nullable=True),
    sa.Column('ModifyDate', mysql.DATETIME(), nullable=True),
    sa.Column('Role_Id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('User_Id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('Auth_Id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('sys_log',
    sa.Column('Id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('BeginDate', mysql.DATETIME(), nullable=True),
    sa.Column('BrowserType', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('ElapsedTime', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('EndDate', mysql.DATETIME(), nullable=True),
    sa.Column('ExceptionInfo', mysql.LONGTEXT(), nullable=True),
    sa.Column('LogType', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('RequestParameter', mysql.LONGTEXT(), nullable=True),
    sa.Column('ResponseParameter', mysql.LONGTEXT(), nullable=True),
    sa.Column('Role_Id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ServiceIP', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('Success', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Url', mysql.TEXT(), nullable=True),
    sa.Column('UserIP', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('UserName', mysql.TEXT(), nullable=True),
    sa.Column('User_Id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('task_server',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('server_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('server_account', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('server_password', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('server_ip', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('port', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('private_key_src', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('public_key_src', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('conn_type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('detail', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('update_time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sys_conf',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('type', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('info', mysql.VARCHAR(length=4000), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=3, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('sys_conf', schema=None) as batch_op:
        batch_op.create_index('type', ['type'], unique=False)

    op.create_table('sys_menu',
    sa.Column('Menu_Id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('MenuName', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('Auth', mysql.TEXT(), nullable=True),
    sa.Column('Icon', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Description', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Enable', mysql.TINYINT(display_width=4), autoincrement=False, nullable=True),
    sa.Column('OrderNo', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('TableName', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('ParentId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('Url', mysql.TEXT(), nullable=True),
    sa.Column('CreateDate', mysql.DATETIME(), nullable=True),
    sa.Column('Creator', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('ModifyDate', mysql.DATETIME(), nullable=True),
    sa.Column('Modifier', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('MenuType', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('Menu_Id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('admin_online',
    sa.Column('session_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('login_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('dept_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ip_addr', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('login_location', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('browser', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('os', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('start_timestamp', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('last_access_time', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('expire_time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('auth',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('auth_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('auth_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('pid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('sort', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('icon', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('is_show', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('power_type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('create_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('update_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sys_province',
    sa.Column('ProvinceId', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('ProvinceCode', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('ProvinceName', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('RegionCode', mysql.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('ProvinceId'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('sys_dictionary',
    sa.Column('Dic_ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('Config', mysql.TEXT(), nullable=True),
    sa.Column('CreateDate', mysql.DATETIME(), nullable=True),
    sa.Column('CreateID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Creator', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('DBServer', mysql.TEXT(), nullable=True),
    sa.Column('DbSql', mysql.TEXT(), nullable=True),
    sa.Column('DicName', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('DicNo', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('Enable', mysql.TINYINT(display_width=4), autoincrement=False, nullable=False),
    sa.Column('Modifier', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('ModifyDate', mysql.DATETIME(), nullable=True),
    sa.Column('ModifyID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('OrderNo', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ParentId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('Remark', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('Dic_ID'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('sys_workflowtable',
    sa.Column('WorkFlowTable_Id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('WorkFlow_Id', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('WorkName', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('WorkTableKey', mysql.VARCHAR(length=200), nullable=True, comment='表主键id'),
    sa.Column('WorkTable', mysql.VARCHAR(length=200), nullable=True, comment='表名'),
    sa.Column('WorkTableName', mysql.VARCHAR(length=200), nullable=True, comment='表中文名'),
    sa.Column('CurrentOrderId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('AuditStatus', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('CreateDate', mysql.DATETIME(), nullable=True),
    sa.Column('CreateID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Creator', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('Enable', mysql.TINYINT(display_width=4), autoincrement=False, nullable=True),
    sa.Column('Modifier', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('ModifyDate', mysql.DATETIME(), nullable=True),
    sa.Column('ModifyID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('CurrentStepId', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('StepName', mysql.TEXT(), nullable=True),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('sys_role',
    sa.Column('Role_Id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('CreateDate', mysql.DATETIME(), nullable=True),
    sa.Column('Creator', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('DeleteBy', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('DeptName', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Dept_Id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Enable', mysql.TINYINT(display_width=4), autoincrement=False, nullable=True),
    sa.Column('Modifier', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('ModifyDate', mysql.DATETIME(), nullable=True),
    sa.Column('OrderNo', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ParentId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('RoleName', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('Role_Id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('sys_userdepartment',
    sa.Column('Id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('UserId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('DepartmentId', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('Enable', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('CreateID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Creator', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('CreateDate', mysql.DATETIME(), nullable=True),
    sa.Column('ModifyID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Modifier', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ModifyDate', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('admin',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('login_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('real_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('level', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('role_ids', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('avatar', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('remark', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('salt', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('last_ip', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('last_login', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('create_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('update_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('updated_at', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sys_user',
    sa.Column('User_Id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('Role_Id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('RoleName', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('PhoneNo', mysql.VARCHAR(length=11), nullable=True),
    sa.Column('Remark', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Tel', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('UserName', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('UserPwd', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('UserTrueName', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('DeptName', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('Dept_Id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('Enable', mysql.TINYINT(display_width=4), autoincrement=False, nullable=False),
    sa.Column('Gender', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('HeadImageUrl', mysql.TEXT(), nullable=True),
    sa.Column('IsRegregisterPhone', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('LastLoginDate', mysql.DATETIME(), nullable=True),
    sa.Column('LastModifyPwdDate', mysql.DATETIME(), nullable=True),
    sa.Column('Address', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('AppType', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('AuditDate', mysql.DATETIME(), nullable=True),
    sa.Column('AuditStatus', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Auditor', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('OrderNo', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Token', mysql.TEXT(), nullable=True),
    sa.Column('CreateID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('CreateDate', mysql.DATETIME(), nullable=True),
    sa.Column('Creator', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Mobile', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('Modifier', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('ModifyDate', mysql.DATETIME(), nullable=True),
    sa.Column('ModifyID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('DeptIds', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('User_Id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('sys_tablecolumn',
    sa.Column('ColumnId', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('ApiInPut', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ApiIsNull', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ApiOutPut', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ColSize', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ColumnCNName', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('ColumnName', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('ColumnType', mysql.LONGTEXT(), nullable=True),
    sa.Column('ColumnWidth', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Columnformat', mysql.LONGTEXT(), nullable=True),
    sa.Column('CreateDate', mysql.DATETIME(), nullable=True),
    sa.Column('CreateID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Creator', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('DropNo', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('EditColNo', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('EditRowNo', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('EditType', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Enable', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('IsColumnData', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('IsDisplay', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('IsImage', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('IsKey', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('IsNull', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('IsReadDataset', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Maxlength', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Modifier', mysql.LONGTEXT(), nullable=True),
    sa.Column('ModifyDate', mysql.DATETIME(), nullable=True),
    sa.Column('ModifyID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('OrderNo', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Script', mysql.LONGTEXT(), nullable=True),
    sa.Column('SearchColNo', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('SearchRowNo', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('SearchType', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Sortable', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('TableName', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Table_Id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('ColumnId'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('sys_workflowtablestep',
    sa.Column('Sys_WorkFlowTableStep_Id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('WorkFlowTable_Id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('WorkFlow_Id', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('StepId', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('StepName', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('StepType', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('StepValue', mysql.TEXT(), nullable=True),
    sa.Column('OrderId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('AuditId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='审核人id'),
    sa.Column('Auditor', mysql.VARCHAR(length=50), nullable=True, comment='审核人'),
    sa.Column('AuditStatus', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='审核状态'),
    sa.Column('AuditDate', mysql.DATETIME(), nullable=True),
    sa.Column('Remark', mysql.TEXT(), nullable=True),
    sa.Column('CreateDate', mysql.DATETIME(), nullable=True),
    sa.Column('CreateID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Creator', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('Enable', mysql.TINYINT(display_width=4), autoincrement=False, nullable=True),
    sa.Column('Modifier', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('ModifyDate', mysql.DATETIME(), nullable=True),
    sa.Column('ModifyID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('StepAttrType', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('ParentId', mysql.TEXT(), nullable=True),
    sa.Column('NextStepId', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('Weight', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('Sys_WorkFlowTableStep_Id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('sys_city',
    sa.Column('CityId', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('CityCode', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('CityName', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('ProvinceCode', mysql.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('CityId'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('role',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('role_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('detail', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('create_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('update_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sys_workflow',
    sa.Column('WorkFlow_Id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('WorkName', mysql.VARCHAR(length=200), nullable=False, comment='流程名称'),
    sa.Column('WorkTable', mysql.VARCHAR(length=200), nullable=False, comment='表名'),
    sa.Column('WorkTableName', mysql.VARCHAR(length=200), nullable=True, comment='功能菜单'),
    sa.Column('NodeConfig', mysql.LONGTEXT(), nullable=True, comment='节点信息'),
    sa.Column('LineConfig', mysql.LONGTEXT(), nullable=True, comment='连接配置'),
    sa.Column('Remark', mysql.TEXT(), nullable=True, comment='备注'),
    sa.Column('Weight', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='权重'),
    sa.Column('CreateDate', mysql.DATETIME(), nullable=True),
    sa.Column('CreateID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Creator', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('Enable', mysql.TINYINT(display_width=4), autoincrement=False, nullable=True),
    sa.Column('Modifier', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('ModifyDate', mysql.DATETIME(), nullable=True),
    sa.Column('ModifyID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('AuditingEdit', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('WorkFlow_Id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('sys_tableinfo',
    sa.Column('Table_Id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('CnName', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('ColumnCNName', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('DBServer', mysql.TEXT(), nullable=True),
    sa.Column('DataTableType', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('DetailCnName', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('DetailName', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('EditorType', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('Enable', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ExpressField', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('FolderName', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Namespace', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('OrderNo', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ParentId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('RichText', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('SortName', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('TableName', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('TableTrueName', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('UploadField', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('UploadMaxCount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('Table_Id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('sys_workflowstep',
    sa.Column('WorkStepFlow_Id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('WorkFlow_Id', mysql.VARCHAR(length=36), nullable=True, comment='流程主表id'),
    sa.Column('StepId', mysql.VARCHAR(length=100), nullable=True, comment='流程节点Id'),
    sa.Column('StepName', mysql.VARCHAR(length=200), nullable=True, comment='节点名称'),
    sa.Column('StepType', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='节点类型(1=按用户审批,2=按角色审批)'),
    sa.Column('StepValue', mysql.TEXT(), nullable=True, comment='审批用户id或角色id'),
    sa.Column('OrderId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Remark', mysql.TEXT(), nullable=True, comment='备注'),
    sa.Column('CreateDate', mysql.DATETIME(), nullable=True),
    sa.Column('CreateID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Creator', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('Enable', mysql.TINYINT(display_width=4), autoincrement=False, nullable=True),
    sa.Column('Modifier', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('ModifyDate', mysql.DATETIME(), nullable=True),
    sa.Column('ModifyID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('NextStepIds', mysql.TEXT(), nullable=True),
    sa.Column('ParentId', mysql.TEXT(), nullable=True),
    sa.Column('AuditRefuse', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('AuditBack', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('AuditMethod', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('SendMail', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Filters', mysql.TEXT(), nullable=True),
    sa.Column('StepAttrType', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Weight', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('pear_config',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('config_type', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('config_data', mysql.VARCHAR(length=3000), nullable=True),
    sa.Column('config_status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('updated_at', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sys_workflowtableauditlog',
    sa.Column('Id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('WorkFlowTable_Id', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('WorkFlowTableStep_Id', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('StepId', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('StepName', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('AuditId', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Auditor', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('AuditStatus', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('AuditResult', mysql.TEXT(), nullable=True),
    sa.Column('AuditDate', mysql.DATETIME(), nullable=True),
    sa.Column('Remark', mysql.TEXT(), nullable=True),
    sa.Column('CreateDate', mysql.DATETIME(), nullable=True),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('sys_quartzoptions',
    sa.Column('Id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('TaskName', mysql.TEXT(), nullable=False, comment='任务名称'),
    sa.Column('GroupName', mysql.TEXT(), nullable=False, comment='任务分组'),
    sa.Column('CronExpression', mysql.VARCHAR(length=100), nullable=False, comment='Corn表达式'),
    sa.Column('Method', mysql.VARCHAR(length=50), nullable=True, comment='请求方式'),
    sa.Column('ApiUrl', mysql.TEXT(), nullable=True, comment='Url地址'),
    sa.Column('AuthKey', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('AuthValue', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('Describe', mysql.TEXT(), nullable=True, comment='描述'),
    sa.Column('LastRunTime', mysql.DATETIME(), nullable=True, comment='最后执行执行'),
    sa.Column('Status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='运行状态'),
    sa.Column('PostData', mysql.LONGTEXT(), nullable=True, comment='post参数'),
    sa.Column('TimeOut', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='超时时间(秒)'),
    sa.Column('CreateID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Creator', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('CreateDate', mysql.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('ModifyID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Modifier', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('ModifyDate', mysql.DATETIME(), nullable=True, comment='修改时间'),
    sa.PrimaryKeyConstraint('Id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('task',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('source_type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('source_server', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('source_path', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('dst_type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('dst_server', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('dst_path', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('exclude_type', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('task_file_num', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sys_quartzlog',
    sa.Column('LogId', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('Id', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('TaskName', mysql.TEXT(), nullable=True, comment='任务名称'),
    sa.Column('ElapsedTime', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='耗时(秒)'),
    sa.Column('StratDate', mysql.DATETIME(), nullable=True, comment='开始时间'),
    sa.Column('EndDate', mysql.DATETIME(), nullable=True, comment='结束时间'),
    sa.Column('Result', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='执行结果'),
    sa.Column('ResponseContent', mysql.LONGTEXT(), nullable=True, comment='返回内容'),
    sa.Column('ErrorMsg', mysql.LONGTEXT(), nullable=True),
    sa.Column('CreateID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Creator', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('CreateDate', mysql.DATETIME(), nullable=True),
    sa.Column('ModifyID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Modifier', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('ModifyDate', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('LogId'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('sys_department',
    sa.Column('DepartmentId', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('DepartmentName', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('DepartmentCode', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('ParentId', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('DepartmentType', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('Enable', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Remark', mysql.TEXT(), nullable=True),
    sa.Column('CreateID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Creator', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('CreateDate', mysql.DATETIME(), nullable=True),
    sa.Column('ModifyID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Modifier', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('ModifyDate', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('DepartmentId'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('task_log',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('task_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('server_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('source_path', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('dst_path', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('size', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sys_dictionarylist',
    sa.Column('DicList_ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('CreateDate', mysql.DATETIME(), nullable=True),
    sa.Column('CreateID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Creator', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('DicName', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('DicValue', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('Dic_ID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Enable', mysql.TINYINT(display_width=4), autoincrement=False, nullable=True),
    sa.Column('Modifier', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('ModifyDate', mysql.DATETIME(), nullable=True),
    sa.Column('ModifyID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('OrderNo', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('Remark', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('DicList_ID'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB',
    mysql_row_format='DYNAMIC'
    )
    op.create_table('login_info',
    sa.Column('info_id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('login_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('ip_addr', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('login_location', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('browser', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('os', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('msg', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('login_time', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('info_id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('oper_log',
    sa.Column('id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('business_type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('method', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('request_method', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('operator_type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('oper_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('dept_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('oper_url', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('oper_ip', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('oper_location', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('oper_param', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('json_result', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('error_msg', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('oper_time', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
